spring:
  # application:
  #   name: '@project.name@'
  # cloud:
  #   config:
  #     enabled: false
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always

logging:
  file:
    path: data/logs
    name: ${logging.file.path}/${spring.application.name}.log

server:
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
  forward-headers-strategy: framework
  http2:
    enabled: true
  port: 8761
  shutdown: graceful

management:
  endpoint:
    configprops:
      show-values: always
    env:
      post:
        enabled: true
      show-values: always
    health:
      group:
        liveness:
          - include:
              - livenessState
            show-components: always
        readiness:
          - include:
              - readinessState
            show-components: always
      probes:
        add-additional-paths: true
        enabled: true
      show-components: always
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true
    git:
      mode: full
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    enable:
      all: true
  server:
    add-application-context-header: true
  zipkin:
    tracing:
      endpoint: http://10.128.24.11:9411/api/v2/spans

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
  instance:
    appname: ${spring.application.name}
    prefer-ip-address: true
    hostname: ${spring.application.name}
    health-check-url-path: ${management.endpoints.web.base-path:/actuator}/health
    status-page-url-path: ${management.endpoints.web.base-path:/actuator}/info
  server:
    batch-replication: true
    enable-replicated-request-compression: true
    number-of-replication-retries: 1
    rate-limiter-enabled: true
  dashboard:
    path: /dashboard
  environment: ${spring.profiles.active:k8s}
  datacenter: ${spring.application.name}
